#!/usr/bin/env python3
"""EAP 17종 카탈로그를 C 표로 변환한다 (빌드 시 1회 실행).

입력  : inputs/eap_source/EAP_invivo_means.csv, 501nm_extended_e1701000.mat
출력  : src/generated/rt_eap_species_data.inc
"""
import numpy as np, pandas as pd, scipy.io as io, hashlib, os, sys
from scipy.fftpack import fft, ifft
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from eap_catalog_freeze import (N_MEDIA, A_SOL_675, CI_KG_M3, NORM_NM,
                                HILBERT_NM, CATALOG, EUK, PROK)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, 'inputs', 'eap_source')
OUT  = os.path.join(ROOT, 'src', 'generated', 'rt_eap_species_data.inc')
WL_LO, WL_HI, WL_STEP = 350.0, 850.0, 1.0          # 산출 파장 격자

def hilbert_imag(x):
    N = len(x); X = fft(x, N); h = np.zeros(N)
    h[0] = 1; h[1:N // 2] = 2.0; h[N // 2] = 1
    return np.imag(ifft(X * h, N))

def logextrap(xq, xp, fp):
    y = np.exp(np.interp(xq, xp, np.log(fp)))
    m = xq < xp[0]
    s = (np.log(fp[10]) - np.log(fp[0])) / (xp[10] - xp[0])
    y[m] = np.exp(np.log(fp[0]) + s * (xq[m] - xp[0]))
    m = xq > xp[-1]
    s = (np.log(fp[-1]) - np.log(fp[-11])) / (xp[-1] - xp[-11])
    y[m] = np.exp(np.log(fp[-1]) + s * (xq[m] - xp[-1]))
    return y

def sha(p):
    return hashlib.sha256(open(p, 'rb').read()).hexdigest()

def main():
    inv = pd.read_csv(os.path.join(SRC, 'EAP_invivo_means.csv'))
    inv = inv.drop(columns=[c for c in inv.columns if c.startswith('Unnamed')])
    W = inv['wavelength'].values
    mf = io.loadmat(os.path.join(SRC, '501nm_extended_e1701000.mat'))['RIs']

    lo, hi, st = HILBERT_NM
    LH = np.arange(lo, hi + st / 2, st)                     # 힐베르트 격자
    LO = np.arange(WL_LO, WL_HI + WL_STEP / 2, WL_STEP)     # 산출 격자
    sel = np.searchsorted(LH, LO)
    inorm = int(np.argmin(np.abs(LH - NORM_NM)))
    ci_mg = CI_KG_M3 * 1e6

    rows = []
    for sid, name, deff, kind in CATALOG:
        p = EUK if kind == 'euk' else PROK
        Vs = p['Vs']
        shape = logextrap(LH, W, inv[name].values)
        kn = (NORM_NM * 1e-9 / N_MEDIA) * (A_SOL_675 * ci_mg / Vs) / (4 * np.pi)
        kshell = shape * (kn / shape[inorm])
        nshell = p['nshell0'] + hilbert_imag(kshell)
        if kind == 'euk':
            kcore = logextrap(LH, mf[:, 5] * 1000.0, np.maximum(mf[:, 0], 1e-12))
            ncore = p['ncore0'] + hilbert_imag(kcore)
        else:
            a, b, c = p['ncore_pow']; ncore = a * LH ** b + c
            a, b, c = p['kcore_pow']; kcore = a * LH ** b + c
        rows.append((sid, name, deff, Vs,
                     nshell[sel], kshell[sel], ncore[sel], kcore[sel]))

    def arr(v):
        return ',\n    '.join(', '.join('%.17g' % x for x in v[i:i + 6])
                              for i in range(0, len(v), 6))

    with open(OUT, 'w') as f:
        f.write('/* Generated by tools/generate_eap_species_catalog.py.'
                '  Do not edit. */\n')
        f.write('/* source EAP_invivo_means.csv sha256 %s */\n'
                % sha(os.path.join(SRC, 'EAP_invivo_means.csv')))
        f.write('/* source 501nm_extended_e1701000.mat sha256 %s */\n'
                % sha(os.path.join(SRC, '501nm_extended_e1701000.mat')))
        f.write('#define RT_EAP_NWL %d\n' % len(LO))
        f.write('#define RT_EAP_WL_LO %.17g\n#define RT_EAP_WL_HI %.17g\n'
                '#define RT_EAP_WL_STEP %.17g\n' % (WL_LO, WL_HI, WL_STEP))
        for sid, name, deff, Vs, ns, ks, nc, kc in rows:
            f.write('\nstatic const char  s%02d_name[] = "%s";\n' % (sid, name))
            f.write('static const double s%02d_deff = %.17g;\n' % (sid, deff))
            f.write('static const double s%02d_vs   = %.17g;\n' % (sid, Vs))
            for tag, v in (('nsh', ns), ('ksh', ks), ('nco', nc), ('kco', kc)):
                f.write('static const double s%02d_%s[RT_EAP_NWL] = {\n    %s\n};\n'
                        % (sid, tag, arr(v)))
        f.write('\nstatic const rt_eap_species_entry_t k_eap_catalog[] = {\n')
        for sid, name, deff, Vs, *_ in rows:
            f.write('    { s%02d_name, &s%02d_deff, &s%02d_vs, s%02d_nsh, '
                    's%02d_ksh, s%02d_nco, s%02d_kco },\n'
                    % (sid, sid, sid, sid, sid, sid, sid))
        f.write('};\n')
    print('생성 완료: %s (%d종 x %d파장)' % (OUT, len(rows), len(LO)))

if __name__ == '__main__':
    main()
